### ISSUE TITLE
shadow in R code boxes

### ISSUE THREAD

**Issue by ginolhac** [koncina/iosp#2] opened 2016-12-01 08:37 UTC
is overlapping the output R code box, see example below

![image](https://cloud.githubusercontent.com/assets/710181/20786963/a9a803a2-b7a9-11e6-8094-ffac120abc88.png)

**Comment by koncina** [comment] 2016-12-01 10:03
This was actually an intended behaviour. The dark blue code appearing in the foreground (have a look at the different shadow sizes on the right side) and the output chunk behind the code but still with a (smaller) shadow.

**Comment by ginolhac** [comment] 2016-12-01 10:38
could we add some space in between?

**Comment by koncina** [comment] 2017-02-13 14:59
Closing as the css code for the shadow changed since this issue was reported...

**Closed as completed by koncina** 2017-02-13 14:59 UTC
